name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: Build and run test
        id: build-and-test
        uses: ./.github/actions/zig-build
        with:
          zig_version: '0.11.0-dev.1711+dc1f50e50'
          command: 'zig build test'

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: zig-out
          path: zig-out
