# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: Build and run test
        id: build-and-test
        uses: ./.github/actions/zig-build
        with:
          zig_version: '0.11.0-dev.1647+c32171991'
          command: 'zig build test'

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: zig-out # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: zig-out
